# Общие версии зависимостей и плагинов, используемые несколькими модулями.

libraryGroup=me.seetch
libraryVersion=1.0.1

# Первая поддерживаемая версия сервера.
paperApiVersion=1.21.4-R0.1-SNAPSHOT
paperweightDevBundleVersion=1.21.4-R0.1-SNAPSHOT

paperweightUserdevVersion=2.0.0-beta.19
shadowPluginVersion=8.3.5
junitBomVersion=5.11.0
mockitoVersion=5.14.2
mockbukkitVersion=4.24.0

org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
